import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense
      fallback={
        <div className="bg-primary absolute z-50 h-screen w-screen"></div>
      }
    >
      <html lang="en">
        <body className={`bg-primary text-secondary font-sans antialiased`}>
          <Navbar />
          {children}
        </body>
      </html>
    </Suspense>
  );
}
